name: drone_data_getter_flutter
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  mqtt_client: any
  meta: any








dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


